In [42]:
import pandas as pd
import numpy as np

## Datasets

In [43]:
# Cargamos los resultados obtenidos por la hipotesis a, es decir, por la regla OneR
data_a = pd.read_csv('mcnemar_a.csv', delimiter=';', header=0)
data_a

inst#                   actual               predicted error  prediction
0        1  1:diaporthe-stem-canker            8:brown-spot     +           1
1        2    15:frog-eye-leaf-spot            8:brown-spot     +           1
2        3  1:diaporthe-stem-canker  14:alternarialeaf-spot     +           1
3        4  1:diaporthe-stem-canker  14:alternarialeaf-spot     +           1
4        5   14:alternarialeaf-spot  14:alternarialeaf-spot   NaN           1
..     ...                      ...                     ...   ...         ...
223    224   14:alternarialeaf-spot  14:alternarialeaf-spot   NaN           1
224    225    15:frog-eye-leaf-spot      4:phytophthora-rot     +           1
225    226    15:frog-eye-leaf-spot      4:phytophthora-rot     +           1
226    227         5:brown-stem-rot          2:charcoal-rot     +           1
227    228   14:alternarialeaf-spot  14:alternarialeaf-spot   NaN           1

[228 rows x 5 columns]

In [44]:
# Cargamos los resultados obtenidos por la hipotesis b, es decir, por el clasificador J48
data_b = pd.read_csv('mcnemar_b.csv', delimiter=';', header=0)
data_b

inst#                   actual                predicted error  prediction
0        1  1:diaporthe-stem-canker  1:diaporthe-stem-canker   NaN       1.000
1        2    15:frog-eye-leaf-spot   14:alternarialeaf-spot     +       0.853
2        3  1:diaporthe-stem-canker  1:diaporthe-stem-canker   NaN       1.000
3        4  1:diaporthe-stem-canker  1:diaporthe-stem-canker   NaN       1.000
4        5   14:alternarialeaf-spot   14:alternarialeaf-spot   NaN       0.955
..     ...                      ...                      ...   ...         ...
223    224   14:alternarialeaf-spot   14:alternarialeaf-spot   NaN       0.853
224    225    15:frog-eye-leaf-spot    15:frog-eye-leaf-spot   NaN       0.976
225    226    15:frog-eye-leaf-spot    15:frog-eye-leaf-spot   NaN       0.976
226    227         5:brown-stem-rot         5:brown-stem-rot   NaN       1.000
227    228   14:alternarialeaf-spot   14:alternarialeaf-spot   NaN       0.853

[228 rows x 5 columns]

Como podemos obervar, el conjunto de datos presenta 5 columnas: 
- **inst#** indica el numero de instancia
- **actual**: indica el resultado esperado
- **predicted**: indica el resultado predecido
- **error**: indica si se ha acertado o no
- **prediction**: porcentaje de predicción

## Cuantificamos el número de instancias bien y mal clasificadas por las hipótesis

### Hiptesis a

##### Mal clasificados

In [75]:
mal_a = np.where(data_a['error']=='+')
mal_a = np.asarray(mal_a)
mal_a

array([[  0,   1,   2,   3,   5,   6,   8,   9,  13,  14,  16,  17,  18,
         20,  22,  23,  24,  25,  27,  28,  29,  30,  32,  33,  36,  38,
         39,  40,  44,  48,  49,  51,  53,  58,  60,  61,  64,  65,  68,
         70,  71,  72,  73,  74,  75,  76,  78,  79,  80,  82,  83,  84,
         85,  86,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        101, 102, 104, 105, 107, 108, 109, 110, 112, 113, 114, 115, 116,
        117, 118, 119, 122, 125, 126, 128, 129, 131, 132, 133, 134, 135,
        137, 138, 139, 140, 141, 142, 144, 145, 148, 149, 150, 151, 152,
        154, 155, 156, 158, 159, 160, 161, 162, 163, 164, 165, 166, 168,
        169, 171, 172, 173, 174, 176, 178, 180, 181, 182, 183, 184, 186,
        187, 188, 190, 192, 193, 194, 195, 196, 197, 198, 199, 200, 202,
        203, 204, 208, 209, 211, 212, 213, 214, 215, 218, 219, 220, 221,
        224, 225, 226]], dtype=int64)

##### Bien clasificados

In [83]:
# Obtenmos los indices de las instancias bien clasificadas por a
bien_a = [i for i in range(228) if i not in mal_a]
bien_a = np.asarray(bien_a)
bien_a

array([  4,   7,  10,  11,  12,  15,  19,  21,  26,  31,  34,  35,  37,
        41,  42,  43,  45,  46,  47,  50,  52,  54,  55,  56,  57,  59,
        62,  63,  66,  67,  69,  77,  81,  87,  99, 100, 103, 106, 111,
       120, 121, 123, 124, 127, 130, 136, 143, 146, 147, 153, 157, 167,
       170, 175, 177, 179, 185, 189, 191, 201, 205, 206, 207, 210, 216,
       217, 222, 223, 227])

### Hipotesis b

##### Mal clasificados

In [84]:
# Obtenemos los indices de las intancias mal clasificadas por b
mal_b = np.where(data_b['error']=='+')
mal_b = np.asarray(mal_b)
mal_b

array([[  1,  26,  58,  74,  97, 108, 133, 156, 163, 173, 182, 187, 210,
        211]], dtype=int64)

##### Bien clasificados

In [85]:
# Obtenmos los indices de las instancias bien clasificadas por b
bien_b = [i for i in range(228) if i not in mal_b]
bien_b = np.asarray(bien_b)
bien_b

array([  0,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 134, 135, 136,
       137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 157, 158, 159, 160, 161, 162, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 174, 175, 176, 177, 178,
       179, 180, 181, 183, 184, 185, 186, 188, 189, 190, 191, 19

## Tabla de contingencia

#### Mal clasificadas por ha y hb

In [95]:
result1 = np.intersect1d(mal_a, mal_b)
print(result1)
print('Intancias mal clasificadas por ha y hb: ', '\033[1m' + str(len(result1)) + '\033[0m')

[  1  58  74  97 108 133 156 163 173 182 187 211]
Intancias mal clasificadas por ha y hb:  12


#### Bien clasificadas por ha pero mal clasificadas por hb

In [99]:
result2 = np.intersect1d(bien_a, mal_b)
print(result2)
print('Intancias bien clasificadas por ha pero mal clasificadas por hb: ', '\033[1m' + str(len(result2)) + '\033[0m')

[ 26 210]
Intancias bien clasificadas por ha pero mal clasificadas por hb:  2


#### Mal clasificadas por ha pero bien clasificadas por hb

In [97]:
result3 = np.intersect1d(mal_a, bien_b)
print(result3)
print('Intancias mal clasificadas por ha pero bien clasificadas por hb: ', '\033[1m' + str(len(result3)) + '\033[0m')

[  0   2   3   5   6   8   9  13  14  16  17  18  20  22  23  24  25  27
  28  29  30  32  33  36  38  39  40  44  48  49  51  53  60  61  64  65
  68  70  71  72  73  75  76  78  79  80  82  83  84  85  86  88  89  90
  91  92  93  94  95  96  98 101 102 104 105 107 109 110 112 113 114 115
 116 117 118 119 122 125 126 128 129 131 132 134 135 137 138 139 140 141
 142 144 145 148 149 150 151 152 154 155 158 159 160 161 162 164 165 166
 168 169 171 172 174 176 178 180 181 183 184 186 188 190 192 193 194 195
 196 197 198 199 200 202 203 204 208 209 212 213 214 215 218 219 220 221
 224 225 226]
Intancias mal clasificadas por ha pero bien clasificadas por hb:  147


#### Bien clasificadas por ha y hb

In [98]:
result4 = np.intersect1d(bien_a, bien_b)
print(result4)
print('Intancias bien clasificadas por ha y hb: ', '\033[1m' + str(len(result4)) + '\033[0m')

[  4   7  10  11  12  15  19  21  31  34  35  37  41  42  43  45  46  47
  50  52  54  55  56  57  59  62  63  66  67  69  77  81  87  99 100 103
 106 111 120 121 123 124 127 130 136 143 146 147 153 157 167 170 175 177
 179 185 189 191 201 205 206 207 216 217 222 223 227]
Intancias bien clasificadas por ha y hb:  67


### Implementacion del Test de McNemar en Python

In [104]:
# Example of calculating the mcnemar test
from statsmodels.stats.contingency_tables import mcnemar

table = [[12, 147],
         [2, 67]]

# calculate mcnemar test
result = mcnemar(table, exact=True)

print('statistic=%.3f, p-value=%.3f' % (result.statistic, result.pvalue))
# interpret the p-value
alpha = 0.05
if result.pvalue > alpha:
    print('Mismas proporciones de error (se acepta H0)')
else:
    print('Diferentes proporciones de error (rechazamos H0)')

statistic=2.000, p-value=0.000
Diferentes proporciones de error (rechazamos H0)
